# This file orchestrates the release workflow of this repository (creating, bumping and pushing tags into releases, etc.)

name: release

on:
  push:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:

  Release:

    name: Release
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # Create a GH Release using the output of the tag_version step
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
    